# Generated by Django 2.1.4 on 2018-12-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
